name: 'Foundry Package Release'
description: 'Publish Foundry VTT packages via the Foundry API'
author: 'neovatar'

inputs:
  name:
    description: 'Name to greet'
    required: true
    default: 'World'
  greeting:
    description: 'Greeting to use'
    required: false
    default: 'Hello'

outputs:
  message:
    description: 'The message produced by the action'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/neovatar/foundry-package-release@sha256:0c08e870d0210c3e8bee438f9b5917d4dbf7ca0ed424dd8ed0bcd10e4ffcc7d6'

branding:
  icon: 'upload-cloud'
  color: 'purple'
