name: 'Foundry Package Release'
description: 'Publish Foundry VTT packages via the Foundry API'
author: 'neovatar'

inputs:
  name:
    description: 'Name to greet'
    required: true
    default: 'World'
  greeting:
    description: 'Greeting to use'
    required: false
    default: 'Hello'

outputs:
  message:
    description: 'The message produced by the action'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/neovatar/foundry-package-release@sha256:edda628b183e93d6bb0ed567f313d40dfbb3addc4914daac2fc2a93def1902d4'

branding:
  icon: 'upload-cloud'
  color: 'purple'
